title: Hydra Password Manager
theme: jekyll-theme-midnight
show_downloads: true 
zip_url: https://github.com/chaosandcarbs/hydra/archive/refs/tags/v0.3.0.zip
tar_url: https://github.com/chaosandcarbs/hydra/archive/refs/tags/v0.3.0.tar.gz
win_url: https://github.com/chaosandcarbs/hydra/releases/download/v0.3.0/Hydra.exe
android_url: https://github.com/chaosandcarbs/hydra/releases/download/v0.3.0/hydra-0.3.0-arm64-debug.apk
